In [1]:
import numpy as np

In [8]:
data_array = np.zeros(45)
data_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
data_array[:11] = a

In [13]:
data_array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
        #For labeling the excel sheet
        param_names = ['k1_true', 'k2_true', 'k3_true', 'k4_true',      #0,1,2,3
                       'b1_true', 'b2_true', 'b3_true',                  #4,5,6
                       'F_true', 'm1_true', 'm2_true', 'm3_true',        #7,8,9,10
                       'k1_guess', 'k2_guess', 'k3_guess', 'k4_guess',    #11,12,13,14
                       'b1_guess', 'b2_guess', 'b3_guess',                  #15,16,17
                       'F_guess', 'm1_guess', 'm2_guess', 'm3_guess',        #18,19,20,21
                       'k1_recovered', 'k2_recovered', 'k3_recovered', 'k4_recovered', #22,23,24,25
                       'b1_recovered', 'b2_recovered', 'b3_recovered',          #26,27,28
                       'F_recovered', 'm1_recovered', 'm2_recovered', 'm3_recovered', #29,30,31,32
                       'e_k1', 'e_k2', 'e_k3', 'e_k4',                       #33, 34, 35, 36
                       'e_b1', 'e_b2', 'e_b3', 'e_F',                     #37, 38, 39, 40
                       'e_m1', 'e_m2', 'e_m3',                            #41, 42, 43
                       'Amp1_rsqrd', 'Amp2_rsqrd', 'Amp3_rsqrd',             #44, 45, 46
                       'Phase1_rsqrd', 'Phase2_rsqrd', 'Phase3_rsqrd', '<e>']  #47, 48, 49, 50   So there are 51 columns

In [23]:
param_names[50]

'<e>'